### ISSUE TITLE
The "scones" command still doesn't work

### ISSUE THREAD

**Issue by riders994** [barretobrock/cah_bot#15]
Command should cause a scone to appear on my desk

**Comment by barretobrock** [comment]
Unfortunately, this command has been borked for some time now due to an upstream dependency. Our developers haven't had luck with finding a working solution with the current version of the matter package. The best we've been able to do is approximate where the closest scone is to your current location, though there are issues with that as well: 

- The service often incorrectly recommends muffins, slightly less-than-savory biscuits and schooners instead of the expected scones. 
- When a scone is properly found, 80% of the time it is old/stale.
- The service is not supported outside of certain regions having access to open source scone tracking APIs (ScAPI)
